# Generated by Django 3.2.1 on 2021-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trujoyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_ground',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
