# Generated by Django 3.2.1 on 2021-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trujoyapp', '0003_alter_book_ground_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ground',
            name='event',
            field=models.CharField(default='birthday', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_ground',
            name='price',
            field=models.FloatField(default=40000),
            preserve_default=False,
        ),
    ]
