# Generated by Django 3.2.1 on 2021-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trujoyapp', '0004_auto_20210517_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ground',
            name='people',
            field=models.CharField(choices=[('1', '50-100'), ('2', '100-300'), ('3', '300-500'), ('4', '500-1000'), ('5', '1000+')], default='50-100', max_length=10),
            preserve_default=False,
        ),
    ]
