# Generated by Django 3.2.1 on 2021-05-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trujoyapp', '0006_auto_20210518_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ground',
            name='deco',
            field=models.CharField(default='Floral Theme', max_length=40),
            preserve_default=False,
        ),
    ]
